bist_symbols = [

"THYAO.IS","ASELS.IS","EREGL.IS","TUPRS.IS","FROTO.IS",
"KCHOL.IS","SAHOL.IS","AKBNK.IS","ISCTR.IS","YKBNK.IS",
"HALKB.IS","ENKAI.IS","PETKM.IS","SISE.IS","BIMAS.IS",
"ARCLK.IS","TOASO.IS","DOHOL.IS","PGSUS.IS","KOZAL.IS",
"TCELL.IS","ODAS.IS","SASA.IS","KRDMD.IS","ALARK.IS",
"BRYAT.IS","KONTR.IS","GUBRF.IS","CIMSA.IS","OYAKC.IS",
"HEKTS.IS","BRSAN.IS","ULKER.IS","MGROS.IS","TAVHL.IS",
"TKFEN.IS","EGEEN.IS","AKSEN.IS","DOAS.IS","TTRAK.IS"

]