BIST_SYMBOLS = [
"AKBNK.IS","ASELS.IS","BIMAS.IS","EKGYO.IS","EREGL.IS",
"FROTO.IS","GARAN.IS","HEKTS.IS","ISCTR.IS","KCHOL.IS",
"KOZAA.IS","KOZAL.IS","PETKM.IS","SAHOL.IS","SISE.IS",
"TAVHL.IS","TCELL.IS","THYAO.IS","TOASO.IS","TUPRS.IS",
"YKBNK.IS","ALARK.IS","ARCLK.IS","BRSAN.IS","CCOLA.IS",
"CIMSA.IS","DOHOL.IS","ENJSA.IS","ENKAI.IS","GLYHO.IS",
"GUBRF.IS","HALKB.IS","IPEKE.IS","KORDS.IS","MGROS.IS",
"NTHOL.IS","ODAS.IS","OYAKC.IS","PGSUS.IS","SASA.IS",
"SELEC.IS","SMRTG.IS","SOKM.IS","TATGD.IS","TKFEN.IS",
"TRGYO.IS","TSKB.IS","ULKER.IS","VAKBN.IS","VESBE.IS"
]
