SECTORS = {

"ASELS":"DEFENSE",
"BIMAS":"RETAIL",
"EKGYO":"REAL_ESTATE",
"ENKAI":"CONSTRUCTION",
"EREGL":"STEEL",
"FROTO":"AUTOMOTIVE",
"KCHOL":"HOLDING",
"PETKM":"PETROCHEM",
"TCELL":"TELECOM",
"TUPRS":"ENERGY"

}


def get_sector(symbol):

    return SECTORS.get(symbol,"OTHER")
