BIST_SYMBOLS = [

"AEFES","AGHOL","AHGAZ","AKBNK","AKCNS","AKFGY","AKSA","AKSEN","ALARK",
"ALBRK","ALFAS","ARCLK","ASELS","ASTOR","BIMAS","BRYAT","CCOLA","CIMSA",
"DOAS","DOHOL","ECILC","EGEEN","EKGYO","ENJSA","ENKAI","EREGL","FROTO",
"GARAN","GESAN","GUBRF","HALKB","HEKTS","ISCTR","ISDMR","KARSN","KCHOL",
"KONTR","KOZAA","KOZAL","KRDMD","LOGO","MAVI","MGROS","ODAS","OTKAR",
"OYAKC","PETKM","PGSUS","SAHOL","SASA","SELEC","SISE","SMRTG","SOKM",
"TCELL","THYAO","TKFEN","TOASO","TSKB","TTKOM","TTRAK","TUPRS","ULKER",
"VAKBN","VESBE","VESTL","YKBNK","ZOREN"

]
