from core.ai_filter import ai_filter_stock
from core.trade_journal import save_trade
from core.portfolio_manager import add_position
from tg.notifier import TelegramNotifier
from config import (
    TELEGRAM_TOKEN,
    TELEGRAM_CHAT_ID
)

bot = TelegramNotifier(
    TELEGRAM_TOKEN,
    TELEGRAM_CHAT_ID
)

symbols = [
    "SASA.IS",
    "SISE.IS",
    "THYAO.IS",
    "TUPRS.IS",
    "ASELS.IS",
    "KCHOL.IS",
    "YKBNK.IS",
    "BIMAS.IS",
    "HEKTS.IS",
    "PETKM.IS",
    "TCELL.IS",
    "GARAN.IS",
    "AKBNK.IS",
    "EREGL.IS"
]

longs = []
neutrals = []
shorts = []

for symbol in symbols:

    try:

        result = ai_filter_stock(symbol)

        if not result:
            continue

        # ATR filtresi
        if result["atr"] < 0.5:
            continue

        signal = result["signal"]

        if signal in [
            "BUY",
            "STRONG BUY"
        ]:

            longs.append(result)

            if (
                result["score"] >= 80
                and result["confidence"] >= 75
            ):

                save_trade(result)
                add_position(result)

        elif signal in [
            "SELL",
            "STRONG SELL"
        ]:

            shorts.append(result)

        else:

            neutrals.append(result)

    except Exception as e:

        print(
            f"[ERROR] "
            f"{symbol} -> {e}"
        )

# BUY SORT

longs = sorted(
    longs,
    key=lambda x: (
        x["score"],
        x["confidence"],
        x["bull_score"],
        x["volume_ratio"]
    ),
    reverse=True
)

# WATCH SORT

neutrals = sorted(
    neutrals,
    key=lambda x: (
        x["score"],
        x["confidence"]
    ),
    reverse=True
)

# SELL SORT

shorts = sorted(
    shorts,
    key=lambda x: (
        x["score"],
        x["bear_score"]
    )
)

report = "📈 BIST AI MARKET REPORT\n\n"

# BUY SIGNALS

report += "🟢 BUY SIGNALS\n"

if longs:

    for item in longs[:10]:

        report += (
            f"{item['symbol']} | "
            f"Score {item['score']} | "
            f"Conf {item['confidence']}% | "
            f"ATR {item['atr']}\n"
        )

else:

    report += "Yok\n"

# WATCH SIGNALS

report += "\n🟡 WATCH SIGNALS\n"

if neutrals:

    for item in neutrals[:10]:

        report += (
            f"{item['symbol']} | "
            f"Score {item['score']}\n"
        )

else:

    report += "Yok\n"

# SELL SIGNALS

report += "\n🔴 SELL SIGNALS\n"

if shorts:

    for item in shorts[:10]:

        report += (
            f"{item['symbol']} | "
            f"Score {item['score']}\n"
        )

else:

    report += "Yok\n"

# MARKET PULSE

report += "\n📊 MARKET PULSE\n"

report += f"Bullish : {len(longs)}\n"
report += f"Neutral : {len(neutrals)}\n"
report += f"Bearish : {len(shorts)}\n"

# MARKET MOOD

if len(longs) >= 5:

    mood = "BULLISH"

elif len(shorts) >= 5:

    mood = "BEARISH"

else:

    mood = "SIDEWAYS"

report += f"\n📈 Market Mood : {mood}\n"

# TOP SIGNAL

if longs:

    best_signal = max(
        longs,
        key=lambda x: (
            x["score"] * 3
            + x["confidence"]
            + x["bull_score"]
            + (x["volume_ratio"] * 10)
        )
    )

    report += "\n🔥 TOP SIGNAL\n\n"

    report += (
        f"{best_signal['symbol']}\n"
        f"AI Score : {best_signal['score']}\n"
        f"Trend : {best_signal['trend']}\n"
        f"Confidence : {best_signal['confidence']}%\n"
        f"ATR : {best_signal['atr']}\n\n"
        f"Entry : {best_signal['entry_price']}\n"
        f"Stop : {best_signal['stop_loss']}\n"
        f"Target 1 : {best_signal['target_1']}\n"
        f"Target 2 : {best_signal['target_2']}\n"
    )

report += "\n⚡ Generated by BIST QUANT ENGINE"

print("\n========== REPORT ==========\n")
print(report)

bot.send(report)