# app/bist30.py

BIST30 = [
    "AKBNK.IS","ASELS.IS","BIMAS.IS","EKGYO.IS","ENJSA.IS",
    "EREGL.IS","FROTO.IS","GARAN.IS","HEKTS.IS","ISCTR.IS",
    "KCHOL.IS","KOZAL.IS","KOZAA.IS","PETKM.IS","PGSUS.IS",
    "SAHOL.IS","SASA.IS","SISE.IS","TAVHL.IS","TCELL.IS",
    "THYAO.IS","TOASO.IS","TTKOM.IS","TUPRS.IS","YKBNK.IS"
]
