BIST100 = [

"AEFES","AGHOL","AKBNK","AKFGY","AKSA","AKSEN","ALARK","ALBRK","ALFAS",
"ARCLK","ASELS","ASTOR","BIMAS","BRYAT","CCOLA","CIMSA","DOAS","DOHOL",
"ECILC","ECZYT","EGEEN","EKGYO","ENJSA","ENKAI","EREGL","FROTO","GARAN",
"GESAN","GUBRF","HALKB","HEKTS","ISCTR","ISMEN","KARSN","KCHOL","KONTR",
"KRDMD","MAVI","MGROS","MIATK","ODAS","OTKAR","OYAKC","PETKM","PGSUS",
"QUAGR","REEDR","SAHOL","SASA","SELEC","SISE","SMRTG","SOKM","TAVHL",
"TCELL","THYAO","TKFEN","TOASO","TSKB","TTRAK","TUPRS","ULKER","VAKBN",
"VESBE","VESTL","YKBNK","YYLGD","ZOREN"

]
